//
//  SingleFileDownloader.swift
//  PCL.Mac
//
//  Created by YiZhiMCQiu on 2025/8/24.
//  Generated by Copilot GPT-5.
//

import Foundation

public class SingleFileDownloader {
    public static func download(
        task: InstallTask? = nil,
        url: URL,
        destination: URL,
        replaceMethod: ReplaceMethod = .skip,
        expectedSHA1: String? = nil,
        progress: ((Double) -> Void)? = nil
    ) async throws {
        // 已存在且指定跳过：若存在且哈希匹配则直接完成（新引擎 FileChecker 内部处理）
        let checker: FileChecker?
        if let expectedSHA1 {
            checker = FileChecker(hash: expectedSHA1)
        } else {
            checker = nil
        }
        let file = PCLNetFile(urls: [url], destination: destination, checker: checker, replaceMethod: replaceMethod)

        try await NetManager.shared.download(file) { p in
            // NetManager 内部已在主线程回调
            task?.currentStagePercentage = p
            progress?(p)
        }
        task?.completeOneFile()
    }
}
